blank_issues_enabled: false
contact_links:
  - name: AI Documentation Search
    url: https://gurubase.io/g/fastendpoints
    about: Use AI powered documentation search to get your questions answered.
  - name: Discord Server
    url: https://discord.gg/ARGPxTukpr
    about: Join our discord server for user support.
