name: Publish Nuget Package

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          #dotnet-quality: 'preview'

      - name: Modify xUnit Runner Config
        run: |
          echo '{
            "parallelizeAssembly": false,
            "parallelizeTestCollections": false,
            "diagnosticMessages": false
          }' > Tests/IntegrationTests/FastEndpoints/xunit.runner.json

      - name: Run Tests
        run: dotnet test FastEndpoints.sln --configuration Release --verbosity minimal

      - name: Make Nuget Packages
        run: dotnet pack -c Release

      - name: Publish To Nuget
        run: dotnet nuget push Src/*/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ !contains(github.ref, 'beta') }}
        with:
          draft: false
          name: ${{ github.ref_name }} Release
          body_path: Src/Library/changelog.md
